[General]
Numlock=on

[Theme]
Current=sddm-astronaut-theme
CursorTheme=Bibata-Modern-Classic
CursorSize=48

[X11]
# Greeter X11 (fiable avec NVIDIA) rendu en HiDPI pour la TV 4K
ServerArguments=-nolisten tcp -dpi 192
